.authenticate-to-npmjs:
  - &authenticate-to-npmjs |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

stages:
  - build
  - publish

build-node-v12:
  stage: build
  image: node:12.0.0-alpine
  script:
    - node --version
    - npm --version
    - npm run build

build-node-v14:
  stage: build
  image: node:14.0.0-alpine
  script:
    - node --version
    - npm --version
    - npm run build

build-node-v16:
  stage: build
  image: node:16.0.0-alpine
  script:
    - node --version
    - npm --version
    - npm run build

publish:
  stage: publish
  image: node:12-alpine
  script:
    - *authenticate-to-npmjs
    - npm install
    - npm run make-distribution
    - cd lib/main
    - npm shrinkwrap
    - export RM_TMP_TAG=cicd-$(date +%s)
    - npm publish --access public --tag $RM_TMP_TAG
    - ../../tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
